import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

const COLORS = {
  primary: [79, 70, 229],
  success: [22, 163, 74],
  warning: [245, 158, 11],
  danger: [239, 68, 68],
  info: [37, 99, 235],
  muted: [107, 114, 128],
  text: [17, 24, 39],
  lightText: [156, 163, 175],
  border: [229, 231, 235],
  headerBg: [249, 250, 251],
};

const STATUS_COLORS = {
  completed: COLORS.success,
  done: COLORS.success,
  "in progress": COLORS.info,
  pending: COLORS.warning,
  failed: COLORS.danger,
  abandoned: COLORS.muted,
  overdue: COLORS.danger,
};

export function createDoc() {
  return new jsPDF();
}

export function getPageWidth(doc) {
  return doc.internal.pageSize.getWidth();
}

export function addLogo(doc, y = 20) {
  doc.setFillColor(...COLORS.primary);
  doc.roundedRect(20, y, 8, 8, 2, 2, "F");
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.text);
  doc.text("PMS", 32, y + 6.5);
  return y + 18;
}

export function addTitle(doc, title, y, opts = {}) {
  const pageWidth = getPageWidth(doc);
  const centerX = opts.center !== false;
  doc.setFontSize(opts.fontSize || 18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.text);
  doc.text(title, centerX ? pageWidth / 2 : 20, y, centerX ? { align: "center" } : undefined);
  return y + (opts.spacing || 12);
}

export function addSubtitle(doc, text, y, opts = {}) {
  const pageWidth = getPageWidth(doc);
  doc.setFontSize(opts.fontSize || 10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COLORS.lightText);
  doc.text(text, pageWidth / 2, y, { align: "center" });
  return y + (opts.spacing || 8);
}

export function addDivider(doc, y) {
  const pageWidth = getPageWidth(doc);
  doc.setDrawColor(...COLORS.border);
  doc.line(20, y, pageWidth - 20, y);
  return y + 8;
}

export function addSectionTitle(doc, title, y) {
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.text);
  doc.text(title, 20, y);
  return y + 8;
}

export function addStatCards(doc, stats, y) {
  const pageWidth = getPageWidth(doc);
  const cardWidth = (pageWidth - 50) / stats.length;

  stats.forEach((stat, i) => {
    const x = 20 + i * cardWidth + 2;
    doc.setDrawColor(...COLORS.border);
    doc.roundedRect(x, y, cardWidth - 4, 22, 3, 3, "S");
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...COLORS.muted);
    doc.text(stat.label, x + (cardWidth - 4) / 2, y + 7, { align: "center" });
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...(stat.color || COLORS.primary));
    doc.text(String(stat.value), x + (cardWidth - 4) / 2, y + 16, { align: "center" });
  });

  return y + 28;
}

export function addAutoTable(doc, headers, rows, y, opts = {}) {
  const pageWidth = getPageWidth(doc);
  const tableWidth = opts.width || pageWidth - 40;
  const startX = opts.x || 20;

  autoTable(doc, {
    startY: y,
    margin: { left: startX, right: startX },
    head: [headers],
    body: rows,
    theme: "plain",
    styles: {
      fontSize: 8,
      cellPadding: 4,
      textColor: COLORS.text,
      lineColor: COLORS.border,
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: COLORS.headerBg,
      textColor: COLORS.muted,
      fontStyle: "bold",
      fontSize: 8,
    },
    alternateRowStyles: {
      fillColor: [255, 255, 255],
    },
    columnStyles: opts.columnStyles || {},
    didDrawCell: opts.didDrawCell || null,
  });

  return doc.lastAutoTable.finalY + 5;
}

export function addTimeline(doc, events, y) {
  const pageWidth = getPageWidth(doc);

  events.forEach((ev, i) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    doc.setFillColor(...COLORS.primary);
    doc.circle(24, y + 2, 2, "F");

    if (i < events.length - 1) {
      doc.setDrawColor(...COLORS.border);
      doc.line(24, y + 4, 24, y + 10);
    }

    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...COLORS.muted);
    doc.text(ev.date, 30, y + 3);

    doc.setFont("helvetica", "bold");
    doc.setTextColor(...COLORS.text);
    doc.text(ev.action, 58, y + 3);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(...COLORS.muted);
    doc.text(ev.detail, 130, y + 3);

    y += 10;
  });

  return y + 3;
}

export function addFooter(doc) {
  const totalPages = doc.internal.getNumberOfPages();
  const pageWidth = getPageWidth(doc);

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setDrawColor(...COLORS.border);
    doc.line(20, 280, pageWidth - 20, 280);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...COLORS.lightText);
    doc.text("Generated by PMS", 20, 285);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - 20, 285, { align: "right" });
  }
}

export function savePdf(doc, fileName) {
  doc.save(fileName);
}

export function getStatusColor(status) {
  const s = (status || "").toLowerCase();
  return STATUS_COLORS[s] || COLORS.muted;
}

export function getStatusBgHex(status) {
  const s = (status || "").toLowerCase();
  const map = {
    completed: "#dcfce7",
    done: "#dcfce7",
    "in progress": "#dbeafe",
    pending: "#fef3c7",
    failed: "#fef2f2",
    abandoned: "#f3f4f6",
    overdue: "#fef2f2",
  };
  return map[s] || "#f3f4f6";
}

export function getStatusTextHex(status) {
  const s = (status || "").toLowerCase();
  const map = {
    completed: "#16a34a",
    done: "#16a34a",
    "in progress": "#2563eb",
    pending: "#d97706",
    failed: "#ef4444",
    abandoned: "#6b7280",
    overdue: "#ef4444",
  };
  return map[s] || "#6b7280";
}

export function checkPageBreak(doc, y, threshold = 270) {
  if (y > threshold) {
    doc.addPage();
    return 20;
  }
  return y;
}

export { COLORS };
